#!/bin/bash

ORIGIN=$(git config --get remote.origin.url | sed -e 's/[^A-Za-z0-9._-]/_/g')
PASSWORD=$(cat $HOME/.gitencrypt/$ORIGIN)
SALT=0123456789abcdef

openssl enc -base64 -aes-256-cbc -S $SALT -k "$PASSWORD"
