#!/bin/bash

SRC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# No salt is needed for decryption.
PASS_FIXED=$(cat $SRC/PASSWORD)

# Error messages are redirect to /dev/null.
openssl enc -d -base64 -aes-256-ctr -k $PASS_FIXED -in "$1" 2> /dev/null || cat "$1"