#!/bin/bash

ORIGIN=$(git config --get remote.origin.url | sed -e 's/[^A-Za-z0-9._-]/_/g')
PASSWORD=$(cat $HOME/.gitencrypt/$ORIGIN)

# If decryption fails, use `cat` instead
# Error messages are redirected to /dev/null
openssl enc -d -base64 -aes-256-cbc -k "$PASSWORD" 2> /dev/null || cat